# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d7d1d3cd64bf0bd0a092d432cb44bdd3f129a0d5a191700d36301b60f9e1563656b8fcd83e316498eccecfdddcb6fe76e07773918cbff2d9f65dec20023f09

test:
  secret_key_base: 2989f6c0c841be591c635638a10deff071a465922034473dbebb7a44bc9be165db99d5d31836859b8220cb751b80264bfe25d661dd53290791021498f4bb5ece

production:
  secret_key_base: f30d9a153c1be79e842dc18eaa6d35be30df0f95c813794eca3d9ef8d75926345c722374ab3fdd323fa1e8ecedae93142f8ba2faca72e742d1f48639f1359042
